# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly

 - package-ecosystem: "pip"
   directory: "/"
   schedule:
     interval: "weekly"
   # Raise pull requests for version updates
   # to pip against the `main` branch
   target-branch: "main"
   # Labels on pull requests for version updates only
   labels:
     - "pip dependencies"
     - "dependencies"
   # Allow up-to-date branches to be rebased
   rebase-strategy: "auto"
   # Specify labels for pull requests
   pull-request-branch-name:
     # Separate sections of the branch name with a hyphen
     separator: "-"
